POST http://localhost:8082/files/param1/param2
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="file"; filename="text1.txt"
Content-Type: text/plain

test1
--boundary
Content-Disposition: form-data; name="fileName"

text1.txt
--boundary
Content-Disposition: form-data; name="tags"

tag1, tag2, tag3
--boundary--