micronaut:
  application:
    name: file-storage-service
  server:
    port: 8082
    multipart:
      enabled: true
      max-file-size: 20971520 # Максимальный размер файла в байтах (20MB)
      max-request-size: 41943040 # Максимальный размер запроса в байтах (40MB)
storage:
  upload-dir: "F:\Temp\file-storage\"